version: "3.8"

services:
  # see https://docs.localstack.cloud/get-started/#docker-compose
  # see https://docs.localstack.cloud/localstack/configuration/
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    networks:
      - testnet
    environment:
      # LocalStack configuration
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=secretsmanager
      # - LOCALSTACK_HOSTNAME=localhost
      # - LOCALSTACK_HOSTNAME_EXTERNAL=localhost
      # AWS Configuration
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_SESSION_TOKEN=test
      # ready hook script configuration
      - SECRET_PREFIX=test-aws-integration/
    volumes:
      - localstack-volume-dir:/var/lib/localstack
      - "./init/ready.d:/etc/localstack/init/ready.d" # ready hooks
      - "/var/run/docker.sock:/var/run/docker.sock" # This host docker socket might be different in Mac. Update accordingly.
volumes:
  localstack-volume-dir:

networks:
  testnet:
    name: beku_w3s_network
    external: true