http-listen-host: "0.0.0.0"
http-listen-port: 9000
http-host-allowlist: "*"

metrics-enabled: true
metrics-host: "0.0.0.0"
metrics-port: 9001
metrics-host-allowlist: "*"

# eth2 subcommand options
eth2.network: "teku/config.yaml"
eth2.keystores-path: "web3signer/interop-keys/keys"
eth2.keystores-passwords-path: "web3signer/interop-keys/passwords"
eth2.slashing-protection-enabled: false