version: '3.8'

services:
  web3signer_migrations:
    container_name: 'web3signer-sql-scripts'
    user: root
    image: "consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    volumes:
      - migration-sql:/flyway/sql/:w
    networks:
      - testnet
    entrypoint: ["sh", "-c", "rm /flyway/sql/*.sql; cp /opt/web3signer/migrations/postgresql/*.sql /flyway/sql/; echo \"Number of SQL files copied: $(ls -1 /flyway/sql/*.sql | wc -l)\""]

  db:
    image: "bitnami/postgresql:${PG_TAG:-14}"
    container_name: 'web3signer-postgresql'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web3signer
      - POSTGRES_PORT_NUMBER=5432 
    ports:
      - '5432:5432'
    networks:
      - testnet
    volumes: 
      - dbdata:/bitnami/postgresql
    depends_on:
      web3signer_migrations:
        condition: service_completed_successfully

  flyway:
    image: "flyway/flyway:${FLYWAY_TAG:-latest}"
    container_name: 'web3signer-flyway'
    command: -url=jdbc:postgresql://db:5432/web3signer -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - migration-sql:/flyway/sql/:ro
    depends_on:
      db:
        condition: service_started
      web3signer_migrations:
        condition: service_completed_successfully
    networks:
      - testnet

  web3signer:
    image: "consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    container_name: 'web3signer-primary'
    environment:
      JAVA_OPTS: "-Dlog4j.configurationFile=/var/config/log4j2-w3s.xml"
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./config:/var/config
      - ./uploads/keys:/etc/keys
      - ./uploads/passwords:/etc/passwords
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - testnet
    depends_on:
      flyway:
        condition: service_completed_successfully        

volumes:
  migration-sql:
  dbdata:
  keys:
  passwords:

networks:
  testnet:
    name: beku_w3s_network
