version: '3.8'

services:
  web3signer-init:
    container_name: 'web3signer-init'
    user: root
    image: "consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    volumes:
      - migration-sql:/flyway/sql/:w
      - web3signer-keys:/keys
    networks:
      - testnet
    entrypoint: ["sh", "-c", "chown -R web3signer:web3signer /keys; find /flyway/sql -type f -name \"*.sql\" -exec rm -f {} \\; ; cp /opt/web3signer/migrations/postgresql/*.sql /flyway/sql/; echo \"Number of SQL files copied: $(ls -1 /flyway/sql/*.sql | wc -l)\""]

  flyway:
    image: "flyway/flyway:${FLYWAY_TAG:-latest}"
    container_name: 'web3signer-flyway'
    command: -url=jdbc:postgresql://db:5432/web3signer -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - migration-sql:/flyway/sql/:ro
    depends_on:
      web3signer-init:
        condition: service_completed_successfully
    networks:
      - testnet

  web3signer:
    image: "consensys/web3signer:${WEB3SIGNER_TAG:-develop}"
    container_name: 'web3signer-primary'
    environment:
      JAVA_OPTS: "-Dlog4j.configurationFile=/var/config/log4j2-w3s.xml"
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./web3signer-config/config.yaml:/var/config/config.yaml
      - ./web3signer-config/log4j2-w3s.xml:/var/config/log4j2-w3s.xml
      - ../interop/teku-config/network-config.yaml:/var/config/network-config.yaml
      - ../interop-keys/keys-light:/etc/keys
      - ../interop-keys/passwords:/etc/passwords
      - web3signer-keys:/keys # Used by import API to upload the keys
    ports:
      - "9005:9005"
      - "9006:9006"
    networks:
      - testnet
    depends_on:
      flyway:
        condition: service_completed_successfully        

volumes:
  migration-sql:
  web3signer-keys:

networks:
  testnet:
    name: beku_w3s_network
    external: true
